BEGIN;

DROP TABLE IF EXISTS payments           CASCADE;
DROP TABLE IF EXISTS order_items        CASCADE;
DROP TABLE IF EXISTS orders             CASCADE;
DROP TABLE IF EXISTS ticket_types       CASCADE;
DROP TABLE IF EXISTS event_category_map CASCADE;
DROP TABLE IF EXISTS events             CASCADE;
DROP TABLE IF EXISTS event_categories   CASCADE;
DROP TABLE IF EXISTS venues             CASCADE;
DROP TABLE IF EXISTS users              CASCADE;


-- ============================================================
-- users
-- ============================================================
CREATE TABLE users (
    user_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    first_name     VARCHAR(100)  NOT NULL,
    last_name      VARCHAR(100)  NOT NULL,
    email          VARCHAR(255)  NOT NULL,
    phone          VARCHAR(30),
    password_hash  VARCHAR(255)  NOT NULL,
    account_status VARCHAR(30)   NOT NULL DEFAULT 'active',
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role           VARCHAR(20)   NOT NULL DEFAULT 'user',
    wallet_balance NUMERIC(12,2) NOT NULL DEFAULT 500.00,

    CONSTRAINT users_pkey      PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),

    -- app/services/auth_service.py writes only these two values.
    CONSTRAINT users_role_check
        CHECK (role IN ('user', 'admin')),
    CONSTRAINT users_wallet_balance_check
        CHECK (wallet_balance >= 0)
);

-- Logins resolve the address with LOWER(email), so uniqueness has to be
-- case-insensitive too: users_email_key alone would allow A@x.com and a@x.com
-- to coexist and then match the same login.
CREATE UNIQUE INDEX users_email_lower_unique ON users (LOWER(email));


-- ============================================================
-- venues
-- ============================================================
CREATE TABLE venues (
    venue_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    venue_name  VARCHAR(200) NOT NULL,
    street      VARCHAR(255) NOT NULL,
    city        VARCHAR(120) NOT NULL,
    state       VARCHAR(100) NOT NULL,
    zip_code    VARCHAR(20)  NOT NULL,
    country     VARCHAR(100) NOT NULL DEFAULT 'United States',
    capacity    INTEGER      NOT NULL,
    phone       VARCHAR(30),
    website_url VARCHAR(500),

    CONSTRAINT venues_pkey PRIMARY KEY (venue_id),

    -- A chain venue repeats its name in other cities, so the natural key has
    -- to include the street address.
    CONSTRAINT uq_venues_name_street_city
        UNIQUE (venue_name, street, city),
    CONSTRAINT chk_venues_capacity
        CHECK (capacity > 0)
);


-- ============================================================
-- event_categories
-- ============================================================
CREATE TABLE event_categories (
    category_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    category_name        VARCHAR(100) NOT NULL,
    category_description TEXT,

    CONSTRAINT event_categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT event_categories_category_name_key UNIQUE (category_name)
);


-- ============================================================
-- events
-- ============================================================
CREATE TABLE events (
    event_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    venue_id       BIGINT       NOT NULL,
    title          VARCHAR(255) NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    start_datetime TIMESTAMPTZ  NOT NULL,
    end_datetime   TIMESTAMPTZ  NOT NULL,
    status         VARCHAR(30)  NOT NULL DEFAULT 'scheduled',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT events_pkey PRIMARY KEY (event_id),

    -- RESTRICT: deleting a venue that still hosts events is a data-entry
    -- mistake, not an intent to delete the events.
    CONSTRAINT fk_events_venue
        FOREIGN KEY (venue_id) REFERENCES venues (venue_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_events_end_after_start
        CHECK (end_datetime > start_datetime)
);

CREATE INDEX idx_events_venue_id       ON events (venue_id);
CREATE INDEX idx_events_start_datetime ON events (start_datetime);
CREATE INDEX idx_events_event_type     ON events (event_type);


-- ============================================================
-- event_category_map        (junction: events <-> event_categories)
-- ============================================================
CREATE TABLE event_category_map (
    event_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    -- The composite PK doubles as the "no duplicate tagging" guarantee.
    CONSTRAINT pk_event_category_map PRIMARY KEY (event_id, category_id),

    -- CASCADE both ways: a tag is metadata, never worth blocking a delete.
    CONSTRAINT fk_event_category_map_event
        FOREIGN KEY (event_id) REFERENCES events (event_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_event_category_map_category
        FOREIGN KEY (category_id) REFERENCES event_categories (category_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- The PK already serves lookups that lead with event_id; this index serves
-- the other direction, "every event in category X".
CREATE INDEX idx_event_category_map_category_id
    ON event_category_map (category_id);


-- ============================================================
-- ticket_types
-- ============================================================
CREATE TABLE ticket_types (
    ticket_type_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    event_id           BIGINT        NOT NULL,
    ticket_name        VARCHAR(150)  NOT NULL,
    price              NUMERIC(10,2) NOT NULL,
    total_quantity     INTEGER       NOT NULL,
    available_quantity INTEGER       NOT NULL,
    minimum_purchase   INTEGER       NOT NULL DEFAULT 1,
    maximum_purchase   INTEGER       NOT NULL DEFAULT 10,
    sales_start        TIMESTAMPTZ,
    sales_end          TIMESTAMPTZ,
    status             VARCHAR(30)   NOT NULL DEFAULT 'active',

    CONSTRAINT ticket_types_pkey PRIMARY KEY (ticket_type_id),
    CONSTRAINT uq_ticket_types_event_name UNIQUE (event_id, ticket_name),

    -- CASCADE: a ticket type has no meaning apart from its event.
    CONSTRAINT fk_ticket_types_event
        FOREIGN KEY (event_id) REFERENCES events (event_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT chk_ticket_types_price
        CHECK (price >= 0),
    CONSTRAINT chk_ticket_types_total_quantity
        CHECK (total_quantity >= 0),

    -- The oversell guard. Inventory can never go negative or exceed the
    -- allocation, so two concurrent buyers racing past the application check
    -- still cannot both commit.
    CONSTRAINT chk_ticket_types_available_quantity
        CHECK (available_quantity >= 0
               AND available_quantity <= total_quantity),

    CONSTRAINT chk_ticket_types_minimum_purchase
        CHECK (minimum_purchase > 0),
    CONSTRAINT chk_ticket_types_maximum_purchase
        CHECK (maximum_purchase >= minimum_purchase),
    CONSTRAINT chk_ticket_types_sales_window
        CHECK (sales_start IS NULL
               OR sales_end IS NULL
               OR sales_end > sales_start)
);

CREATE INDEX idx_ticket_types_event_id ON ticket_types (event_id);


-- ============================================================
-- orders
-- ============================================================
CREATE TABLE orders (
    order_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT        NOT NULL,
    order_date   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(30)   NOT NULL DEFAULT 'pending',
    subtotal     NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    service_fee  NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    tax_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT orders_pkey PRIMARY KEY (order_id),

    -- RESTRICT: sales history outlives the account. Deactivate a user with
    -- account_status instead of deleting the row.
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT chk_orders_subtotal     CHECK (subtotal     >= 0),
    CONSTRAINT chk_orders_service_fee  CHECK (service_fee  >= 0),
    CONSTRAINT chk_orders_tax_amount   CHECK (tax_amount   >= 0),
    CONSTRAINT chk_orders_total_amount CHECK (total_amount >= 0)
);

CREATE INDEX idx_orders_user_id    ON orders (user_id);
CREATE INDEX idx_orders_order_date ON orders (order_date);


-- ============================================================
-- order_items               (junction: orders <-> ticket_types)
-- ============================================================
CREATE TABLE order_items (
    order_item_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    order_id       BIGINT        NOT NULL,
    ticket_type_id BIGINT        NOT NULL,
    quantity       INTEGER       NOT NULL,

    -- Price is copied at purchase time: repricing a ticket type must not
    -- rewrite revenue that has already been reported.
    unit_price     NUMERIC(10,2) NOT NULL,

    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),

    -- One line per ticket type per order; buying more means a larger
    -- quantity, not a second row.
    CONSTRAINT uq_order_items_order_ticket_type
        UNIQUE (order_id, ticket_type_id),

    -- CASCADE: line items are parts of an order, not records in their own
    -- right.
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    -- RESTRICT: this is what makes a sold event undeletable. Deleting an
    -- event CASCADEs into ticket_types, and that delete is then blocked here.
    CONSTRAINT fk_order_items_ticket_type
        FOREIGN KEY (ticket_type_id) REFERENCES ticket_types (ticket_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT chk_order_items_quantity   CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_order_items_order_id       ON order_items (order_id);
CREATE INDEX idx_order_items_ticket_type_id ON order_items (ticket_type_id);


-- ============================================================
-- payments
-- ============================================================
CREATE TABLE payments (
    payment_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    order_id              BIGINT        NOT NULL,
    amount                NUMERIC(12,2) NOT NULL,
    payment_method        VARCHAR(50)   NOT NULL,
    payment_status        VARCHAR(30)   NOT NULL,
    transaction_reference VARCHAR(255)  NOT NULL,
    payment_date          TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT payments_pkey PRIMARY KEY (payment_id),

    -- Idempotency key: a retried gateway callback cannot be recorded twice.
    CONSTRAINT payments_transaction_reference_key
        UNIQUE (transaction_reference),

    -- RESTRICT: never orphan or silently erase a financial record.
    -- order_id is deliberately NOT unique, which leaves room for a retry
    -- after a failed attempt and for a later refund row.
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT chk_payments_amount CHECK (amount >= 0)
);

CREATE INDEX idx_payments_order_id       ON payments (order_id);
CREATE INDEX idx_payments_payment_status ON payments (payment_status);

COMMIT;
